### ISSUE TITLE
P01-盛昊天生日礼物🎁页面

### ISSUE THREAD

**Issue by AndersonHJB** [AndersonHJB/AndersonHJB.github.io#8]
# 0. 效果

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e35a7ebc-9e68-4f97-a5af-873ed27dd779">

# 1. anniversary.pug:

```pug
#anniversary-box
    - let anniversary_background = page.top_background
    .author-content.author-content-item.anniversary.single(style=anniversary_background ? `background: url(${anniversary_background}) top / cover no-repeat` : "")
        .card-content
            .author-content-item-tips anniversary
            span.author-content-item-title 喵喵纪念日
            .content-bottom
                .tips 时间如潮水般涌动向前，你会为谁停留片刻？
                .banner-button-group
                  a.banner-button(onclick='pjax.loadUrl("/about/")')
                    i.anzhiyufont.anzhiyu-icon-arrow-circle-right(style='font-size: 1.5rem')
                    span.banner-button-text 我的更多
    #anniversary-main
      each group in site.data.anniversary
        .anniversary-group
          .group-header
            .group-title #{group.class_name} (#{group.anniversaries.length})
            .group-desc #{group.class_desc}

          .anniversary-cards
            each item in group.anniversaries
              .anniversary-card(
                style=`background-color: ${item.color}`,
                data-date=item.date,
                data-lunar=(item.lunar ? 'true' : 'false'),
                data-name=item.name
              )
                .card-content
                  .card-header(style="justify-content: center;")
                    if item.icon
                      img.card-icon(src=item.icon alt="icon")
                    .card-title #{item.name}

                  .card-body(style="background-color: white; padding: 20px; text-align: center;")
                    .countdown-wrapper
                      span.countdown(data-date=item.date data-lunar=item.lunar data-display-mode=item.display_mode) 计算中...
                      .days-label 天后

                  .card-footer
                    .dashed-line(style="border-top: 1px dashed #ccc; margin: 10px 0;")
                    .target-info
                      if item.display_mode === 'elapsed'
                        span.target-label - 起始日 -
                      else
                        span.target-label - 目标日 -
                      br
                      span.target-date(data-date=item.date data-lunar=item.lunar data-display-mode=item.display_mode) 计算中...

                // 根据 show_copyright 显示或隐藏卡片内的版权信息
                if item.show_copyright
                  - let copyrightName = item.copyright_name ? item.copyright_name : '喵喵纪念日'
                  - let copyrightLink = item.copyright_link ? item.copyright_link : 'https://blog.bornforthis.cn/posts/41c7c45e.html'
                  .card-copyright
                    | 版权所有 © #{item.name}
                    a(href=copyrightLink target="_blank") #{copyrightName}
```

# 2. anniversary.js

```javascript
// anniversary.js

// 在使用前确保引入了 canvas-confetti 库
// <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>

function initializeAnniversary() {
    function LunarDate(Year, Month, Day) {
        try {
            let solar = Lunar.fromYmdHms(Year, Month, Day, 0, 0, 0).getSolar();
            return new Date(solar.getYear(), solar.getMonth() - 1, solar.getDay());
        } catch (error) {
            return LunarDate(Year, Month, Day - 1);
        }
    }
    // 计算两个日期之间的天数差
    function daysBetween(date1, date2) {
        const oneDay = 24 * 60 * 60 * 1000;
        return Math.floor((date2 - date1) / oneDay);
    }
    // 计算两个日期之间的周数和天数差
    function weeksAndDaysBetween(date1, date2) {
        const totalDays = daysBetween(date1, date2);
        const weeks = Math.floor(totalDays / 7);
        const days = totalDays % 7;
        return { weeks, days };
    }
    // 计算两个日期之间的月数和天数差
    function monthsAndDaysBetween(date1, date2) {
        let years = date2.getFullYear() - date1.getFullYear();
        let months = date2.getMonth() - date1.getMonth() + years * 12;
        let days = date2.getDate() - date1.getDate();

        if (days < 0) {
            months -= 1;
            let previousMonth = new Date(date2.getFullYear(), date2.getMonth(), 0);
            days += previousMonth.getDate();
        }

        return { months, days };
    }
    // 剩余天数
    function daysLeft(dateStr, isLunar) {
        const [Year, Month, Day] = dateStr.split("-").map(Number);
        let now = new Date();
        now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        let anniversaryDate;
        if (isLunar) {
            anniversaryDate = LunarDate(now.getFullYear(), Month, Day);
            if (anniversaryDate < now) {
                anniversaryDate = LunarDate(now.getFullYear() + 1, Month, Day);
            }
        } else {
            anniversaryDate = new Date(now.getFullYear(), Month - 1, Day);
            if (anniversaryDate < now) {
                anniversaryDate = new Date(now.getFullYear() + 1, Month - 1, Day);
            }
        }
        return daysBetween(now, anniversaryDate);
    }
    // 经过天数
    function totalDays(dateStr, isLunar) {
        const [Year, Month, Day] = dateStr.split("-").map(Number);
        let now = new Date();
        now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        let startDate;
        if (isLunar) {
            startDate = LunarDate(Year, Month, Day);
        } else {
            startDate = new Date(Year, Month - 1, Day);
        }
        return daysBetween(startDate, now);
    }
    // 返回目标或起始日期以及星期几
    function targetDate(dateStr, isLunar) {
        const [Year, Month, Day] = dateStr.split("-").map(Number);
        let now = new Date();
        now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        let anniversaryDate;
        if (isLunar) {
            anniversaryDate = LunarDate(now.getFullYear(), Month, Day);
            if (anniversaryDate < now) {
                anniversaryDate = LunarDate(now.getFullYear() + 1, Month, Day);
            }
        } else {
            anniversaryDate = new Date(now.getFullYear(), Month - 1, Day);
            if (anniversaryDate < now) {
                anniversaryDate = new Date(now.getFullYear() + 1, Month - 1, Day);
            }
        }
        // 获取星期几
        const weekDay = anniversaryDate.toLocaleDateString('zh-CN', { weekday: 'long' });
        // 返回年月日加星期几
        const year = anniversaryDate.getFullYear();
        const month = (anniversaryDate.getMonth() + 1).toString().padStart(2, '0');
        const day = anniversaryDate.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day} (${weekDay})`;
    }
    // 返回目标或起始日期（根据 displayMode）
    function targetOrStartDate(dateStr, isLunar, displayMode) {
        if (displayMode === "elapsed") {
            return dateStr;
        } else {
            return targetDate(dateStr, isLunar);
        }
    }

    const countdownElements = document.querySelectorAll(".countdown");
    let todayAnniversaries = []; // 用于收集今天的纪念日名称

    countdownElements.forEach(function (elem) {
        const dateStr = elem.getAttribute("data-date");
        const isLunar = elem.hasAttribute("data-lunar");
        const displayMode = elem.getAttribute("data-display-mode");
        const card = elem.closest('.anniversary-card'); // 获取对应的卡片元素
        const name = card.getAttribute('data-name'); // 获取纪念日名称

        if (displayMode === "elapsed") {
            elem.dataset.displayState = '0';
            updateElapsedDisplay(elem, dateStr, isLunar, 0);
            elem.addEventListener('click', function () {
                let currentState = parseInt(elem.dataset.displayState);
                currentState = (currentState + 1) % 3;
                elem.dataset.displayState = currentState.toString();
                updateElapsedDisplay(elem, dateStr, isLunar, currentState);
            });

            // 检查是否是纪念日当天
            if (isTodayAnniversary(dateStr, isLunar)) {
                // 对卡片添加烟花效果
                triggerFireworks(card);
                // 收集今天的纪念日名称
                todayAnniversaries.push(name);
            }
        } else {
            let daysText = daysLeft(dateStr, isLunar);
            elem.textContent = daysText;
            elem.nextElementSibling.textContent = "天后";

            // 如果倒计时为0天，表示纪念日当天
            if (parseInt(daysText) === 0) {
                // 对卡片添加烟花效果
                triggerFireworks(card);
                // 收集今天的纪念日名称
                todayAnniversaries.push(name);
            }
        }
    });

    if (todayAnniversaries.length > 0) {
        // 显示横幅通知
        showAnniversaryBanner(todayAnniversaries);
    }

    // 更新elapsed模式下的显示内容
    function updateElapsedDisplay(elem, dateStr, isLunar, displayState) {
        if (displayState === 0) {
            let days = totalDays(dateStr, isLunar);
            elem.textContent = days;
            elem.nextElementSibling.textContent = "天了";
        } else if (displayState === 1) {
            const [Year, Month, Day] = dateStr.split("-").map(Number);
            let now = new Date();
            now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
            let startDate;
            if (isLunar) {
                startDate = LunarDate(Year, Month, Day);
            } else {
                startDate = new Date(Year, Month - 1, Day);
            }

            let { weeks, days } = weeksAndDaysBetween(startDate, now);
            if (days === 0) {
                elem.textContent = weeks;
                elem.nextElementSibling.textContent = "周了";
            } else {
                elem.textContent = `${weeks}周${days}天`;
                elem.nextElementSibling.textContent = "了";
            }
        } else if (displayState === 2) {
            const [Year, Month, Day] = dateStr.split("-").map(Number);
            let now = new Date();
            now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
            let startDate;
            if (isLunar) {
                startDate = LunarDate(Year, Month, Day);
            } else {
                startDate = new Date(Year, Month - 1, Day);
            }

            let { months, days } = monthsAndDaysBetween(startDate, now);
            elem.textContent = `${months}月${days}天`;
            elem.nextElementSibling.textContent = "了";
        }
    }

    // 显示目标或起始日期
    const targetDateElements = document.querySelectorAll(".target-date");
    targetDateElements.forEach(function (elem) {
        const dateStr = elem.getAttribute("data-date");
        const isLunar = elem.hasAttribute("data-lunar");
        const displayMode = elem.getAttribute("data-display-mode");
        elem.textContent = targetOrStartDate(dateStr, isLunar, displayMode);
    });

    // 判断今天是否是纪念日
    function isTodayAnniversary(dateStr, isLunar) {
        const [Year, Month, Day] = dateStr.split("-").map(Number);
        let now = new Date();
        now = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        if (isLunar) {
            let lunarToday = Lunar.fromDate(now);
            return lunarToday.getMonth() === Month && lunarToday.getDay() === Day;
        } else {
            return (now.getMonth() + 1) === Month && now.getDate() === Day;
        }
    }

    // 显示横幅通知
    function showAnniversaryBanner(names) {
        const banner = document.createElement('div');
        banner.className = 'anniversary-banner';
        banner.innerHTML = `
            <div class="banner-content">
                <span>今天是 ${names.join('、')} 纪念日</span>
                <button class="close-button">&times;</button>
            </div>
        `;
        document.body.appendChild(banner);

        // 关闭按钮事件
        banner.querySelector('.close-button').addEventListener('click', function() {
            banner.style.display = 'none';
        });

        // 10 秒后自动关闭
        setTimeout(function() {
            banner.style.display = 'none';
        }, 10000);
    }

    // 触发烟花效果
    function triggerFireworks(element) {
        var rect = element.getBoundingClientRect();
        var x = rect.left + rect.width / 2;
        var y = rect.top + rect.height / 2;

        // 调整为窗口坐标的比例
        var xRatio = x / window.innerWidth;
        var yRatio = y / window.innerHeight;

        var duration = 2 * 1000; // 2秒
        var animationEnd = Date.now() + duration;

        function randomInRange(min, max) {
            return Math.random() * (max - min) + min;
        }

        (function frame() {
            var timeLeft = animationEnd - Date.now();

            if (timeLeft <= 0) return;

            var ticks = Math.max(200, 500 * (timeLeft / duration));

            confetti({
                particleCount: 5,
                startVelocity: 30,
                ticks: ticks,
                origin: {
                    x: xRatio,
                    y: yRatio
                },
                colors: ['#ffae00', '#ff4500', '#ff69b4', '#ba55d3', '#1e90ff'],
                shapes: ['circle', 'square'],
                scalar: randomInRange(0.4, 1),
                drift: randomInRange(-0.4, 0.4)
            });

            requestAnimationFrame(frame);
        })();
    }
}

// 初始页面加载
document.addEventListener("DOMContentLoaded", initializeAnniversary);

// 适配 pjax
document.addEventListener("pjax:complete", initializeAnniversary);
```

# 3. anniversary.css

```css
/* anniversary.css */

/* 背景与页面基本样式 */
body[data-type="anniversary"] #web_bg {
    background: var(--anzhiyu-background);
}

body[data-type="anniversary"] #page {
    border: 0;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    padding: 0 !important;
    background: transparent !important;
}

body[data-type="anniversary"] #page .page-title {
    display: none;
}

/* 卡片整体布局 */
.anniversary-cards {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); /* 响应式布局 */
    gap: 20px;
    padding: 20px;
}

/* 卡片样式 */
.anniversary-card {
    background-color: #f9f9f9;
    border-radius: 10px;
    padding: 20px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
}

.anniversary-card:hover {
    transform: translateY(-10px);
    box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
}

/* 卡片标题和图标水平居中对齐的样式 */
.card-header {
    display: flex;
    justify-content: center; /* 水平居中 */
    align-items: center; /* 垂直居中 */
    margin-bottom: 10px;
}

.card-title {
    font-size: 1.5rem;
    font-weight: bold;
    color: #333;
    text-align: center; /* 文本居中 */
}

.card-icon {
    width: 24px;
    height: 24px;
    margin-right: 10px; /* 图标与标题之间的间距 */
}

/* 白色背景的中间部分 */
.card-body {
    background-color: white;
    padding: 20px;
    margin-bottom: 10px;
    border-radius: 8px;
    color: #333;
    text-align: center;
}

/* 剩余天数与"天后"的样式 */
.countdown-wrapper {
    position: relative;
    display: inline-block;
    font-size: 3rem; /* 设置数字大小 */
    color: #6b4226; /* 设置数字的颜色 */
    font-weight: bold;
}

.days-label {
    position: absolute;
    top: -10px;
    right: -45px;
    background-color: #36c5b2;
    color: white;
    padding: 3px 10px;
    border-radius: 20px;
    font-size: 1rem;
    font-weight: normal;
    display: inline-block;
}

/* 目标日样式 */
.target-info {
    text-align: center;
    font-size: 1rem;
    font-weight: normal;
}

.target-label {
    display: inline-block;
    margin: 0; /* 去掉额外的边距 */
    font-size: 1rem;
    letter-spacing: 2px; /* 保持文字间距 */
}

.target-date {
    display: inline-block; /* 改为inline-block，直接与目标日标签对齐 */
    font-size: 1rem;
    color: #333;
    margin: 0; /* 去掉所有的上下边距 */
    font-weight: normal; /* 去掉加粗效果 */
}

/* 虚线样式 */
.dashed-line {
    border-top: 1px dashed #ccc;
    margin: 10px 0;
}

/* 目标日期与已经过去的天数信息 */
.target-info, .total-days-info {
    font-size: 1rem;
    margin: 5px 0;
    color: #555;
}

/* 响应式布局优化，适配不同设备 */
@media (max-width: 768px) {
    .anniversary-cards {
        grid-template-columns: 1fr;
    }

    .anniversary-card {
        padding: 15px;
    }

    .card-title {
        font-size: 1.2rem;
    }
}

/* 动画效果 */
.anniversary-card {
    transition: all 0.3s ease-in-out;
}

.anniversary-card:hover {
    transform: scale(1.05);
    box-shadow: 0 6px 20px rgba(0, 0, 0, 0.15);
}

/* 版权信息的样式 */
.card-copyright {
    margin-top: 10px;
    font-size: 0.85rem;
    color: #777;
    text-align: right;
}

.card-copyright a {
    color: #007bff;
    text-decoration: none;
}

.card-copyright a:hover {
    text-decoration: underline;
}

/* 分组标题和描述样式 */
.anniversary-group {
    margin-bottom: 40px;
}

.group-header {
    text-align: left; /* 将文本左对齐 */
    margin-bottom: 10px;
}

.group-title {
    font-size: 1.5rem;
    font-weight: bold;
    margin-bottom: 5px;
    text-align: left; /* 分组标题左对齐 */
}

.group-desc {
    font-size: 1rem;
    color: #666;
    margin-bottom: 20px;
    text-align: left; /* 分组描述左对齐 */
}

/* 横幅通知样式 */
.anniversary-banner {
    position: fixed;
    top: 20px;
    left: 50%;
    transform: translateX(-50%);
    background-color: rgba(255, 165, 0, 0.9); /* 橙色背景 */
    color: #fff;
    padding: 15px 30px;
    border-radius: 5px;
    z-index: 1000;
    display: flex;
    align-items: center;
}

.anniversary-banner .banner-content {
    display: flex;
    align-items: center;
}

.anniversary-banner .close-button {
    background: none;
    border: none;
    color: #fff;
    font-size: 20px;
    margin-left: 20px;
    cursor: pointer;
}

/* 由于使用了 canvas-confetti 库，不需要为烟花效果添加额外的 CSS */

```

# 4. _config.anzhiyu.yml

```yml
bottom:
    # 自定义js
    - - <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>
```
